### PR TITLE
Support using ossec.conf template similar to client.pp and wazuh-ossec

### PR DESCRIPTION
**Pull request by blindphaze**
It appears supporting a template was pulled for client.pp but missed for server.pp

### CODE REVIEW

**Comment by jlruizmlg** [comment]
Hi @blindphaze thanks! you are right! , let me take a look and merge as soon as possible!!

**Comment by jlruizmlg** [comment]
hi @blindphaze thanks for your pull request, let me review and merge!

**Comment by blindphaze** [comment]
Are there too many changes now or?

**Comment by jlruizmlg** [comment]
Hi @blindphaze sorry for the late response, this week this pull request will be merged, sorry for the delay!

**Comment by jlruizmlg** [comment]
@blindphaze BTW look amazing the new code :) thanks!

**Comment by blindphaze** [comment]
@jlruizmlg Will you be able to merge any of this down to the puppet3 branch?

**Comment by jlruizmlg** [comment]
@blindphaze if it's compatible yes for sure, this weekend my plan is merge in this actual version and try in the puppet3 branch and merge as well.

Sadly is not easy for me try code in a puppet3 server, but i will figure out.

**Comment by jesuslinares** [comment]
Hello @blindphaze ,

It's been a long time since the last response to this issue, so I'll proceed to close it. If you're still experiencing problems or have any questions about this, please open a new issue on this repository.

Regards,
Team member

**Pull request closed without merging**
