### PR TITLE
Fix duplicate repo

### PR DESCRIPTION
**Pull request by minorOffense**
If you try to install the agent on the manager you get a duplicate declaration error for the wazuh repo.

By changing to use "include" the error can be avoided.

### CODE REVIEW

**Comment by jm404** [comment]
Hi @minorOffense, 

You should never install an Agent in the same endpoint that a Manager is installed. The Wazuh Manager does include monitoring tasks so installing an Agent is not necessary.

Anyway, if you think `include` is better than using `class`, please let us know the details so we can fully understand the pros and cons of it.

Thanks for your contribution!

Best regards,

Jose

**Comment by minorOffense** [comment]
Ok well regardless of having both on the same server. If you should probably use the "include" pattern instead of calling class. If you define a class with no parameters, it's usually better to just use include.

**Comment by minorOffense** [comment]
But thanks for the info about not having both. I'll update our classes to skip it anyways.

**Comment by Zenidd** [comment]
Hello @minorOffense, 

I've tested your PR. In case of a regular deployment (separate agent and manager) it works correctly. When trying to deploy agent and manager on the same node, the duplicate repo error is gone but, in the facts loading stage, another error points a collision among the manifests. 
```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Concat[ossec.conf] is already declared at (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp, line: 320); cannot redeclare (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/manager.pp, line: 380) (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/manager.pp, line: 380, column: 3) on node agent-client-1
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
[root@agent-client-1 vagrant]#
```

Although the use of include is the best practice here, it does not provide better functionality and we prefer to continue using the classes. When using classes, the error description is closer to the restriction (do not install agent and manager together).

Thank you for your contribution @minorOffense. Greetings,
JP

**Pull request closed without merging**
