### PR TITLE
Add a parameter ossec_rootcheck_ignore_list

### PR DESCRIPTION
**Pull request by Hexta**
Add a parameter wazuh::manager::ossec_rootcheck_ignore_list.

### CODE REVIEW

**Comment by Hexta** [comment]
Could anybody please take a look at the PR?

**Comment by manuasir** [comment]
Hey @Hexta , sorry for the late response. Let us give a try to this, launch the tests and if everything fine it'll be shipped. 

Thank you for contributing!

**Comment by rshad** [comment]
Hi @Hexta !

Thank you for contributing for Wazuh, it's really appreciated.

I'll review your changes and test them. I'll be back soon.


Kr,

Rshad

**Comment by rshad** [comment]
Hi!

Puppet Lint Validation Log
```
root@07aa15b95580:~/wazuh-puppet# pdk validate
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.13.0
pdk (INFO): Running all available validators...
┌ [✔] Running metadata validators ...
├── [✔] Checking metadata syntax (metadata.json tasks/*.json).
└── [✔] Checking module metadata style (metadata.json).
┌ [✔] Running puppet validators ...
├── [✔] Checking Puppet manifest syntax (**/*.pp).
└── [✔] Checking Puppet manifest style (**/*.pp).
┌ [✔] Running ruby validators ...
└── [✔] Checking Ruby code style (**/**.rb).
┌ [✔] Running tasks validators ...
├── [✔] Checking task names (tasks/**/*).
└── [✔] Checking task metadata style (tasks/*.json).
┌ [✔] Running yaml validators ...
└── [✔] Checking YAML syntax (**/*.yaml **/*.yml).
info: puppet-epp: ./: Target does not contain any files to validate (["**/*.epp"]).
info: task-name: ./: Target does not contain any files to validate (["tasks/**/*"]).
info: task-metadata-lint: ./: Target does not contain any files to validate (["tasks/*.json"]).root@07aa15b95580:~/wazuh-puppet# git branch
* Hexta/master
  master
root@07aa15b95580:~/wazuh-puppet#
```

Kr,

Rshad

**Comment by rshad** [comment]
Hi @Hexta!

Thank you again for contributing to Wazuh.

Kr,

Rshad

**Pull request merged**
