### PR TITLE
Enforce apt-get update on Debian based system

### PR DESCRIPTION
**Pull request by lemrouch**
after the repository is added and before package is installed

### CODE REVIEW

**Comment by jlruizmlg** [comment]
Hi @lemrouch you are faster than me, you pull request looks great,  i was working in this right now, but i was thinking in change in the params something like the following code: 

```
  ~>
          exec { 'update-apt-wazuh-repo':
            command     => '/usr/bin/apt-get update',
            refreshonly => true
          }
```

And merge Debian and Ubuntu, now all is under the same url, so we can have something like this:

```
      case $::lsbdistcodename {
        /(jessie|wheezy|stretch|sid|precise|trusty|vivid|wily|xenial|yakketi)/: {

          apt::source { 'wazuh':
            ensure   => present,
            comment  => 'This is the WAZUH Ubuntu repository',
            location => 'https://packages.wazuh.com/apt',
            release  => $::lsbdistcodename,
            repos    => 'main',
            include  => {
              'src' => false,
              'deb' => true,
            },
          }
        }
      ~>
              exec { 'update-apt-wazuh-repo':
                command   => '/usr/bin/apt-get update',
                refreshonly => true
              }
        default: { fail('This ossec module has not been tested on your distribution (or lsb package not installed)') }
      }
    }
```

So, we can merge some code, make easier the repo.pp and also avoid code duplications, What do you think? works for you?

**Comment by lemrouch** [comment]
Sure. Duplicit code sux.

**Comment by jlruizmlg** [comment]
@lemrouch perfect!, if you do the changes i merge your pull request or i can the changes, what do you like more?

**Comment by lemrouch** [comment]
Do it please. I'm busy with other stuff.

**Comment by lemrouch** [comment]
On second thought.. isn't _Exec['update-apt-wazuh-repo']_ just duplicate of _Class['apt::update']_?
I hope it won't mess with the whole Apt class. It's maintaining last update time, etc, isn't it?

**Comment by jlruizmlg** [comment]
Hi @lemrouch right, was only a thought, we should use something like the own class for sure! :)

**Comment by jlruizmlg** [comment]
Hi @lemrouch sorry for the late response, we are very busy with the new releases, the code looks perfect, i will go to merge this pull request and modify the repo.pp and unifying debian/ubuntu repositories.

**Pull request merged**
