### PR TITLE
4.2.2 release requires an update to the wazuh api yml template. manifest/manager.pp logic

### PR DESCRIPTION
**Pull request by jakefeasey**
Updated managers manifests and api yaml template to reflect addition of ssl_ciphers and ssl_protocols to Wazuh api, where ssl_cipher has been removed.

### CODE REVIEW

**Comment by vcerenu** [comment]
Wazuh Manager deployment test was performed with branch 4.2.2 on Debian Burster and had the following error.

```
Info: Computing checksum on file /var/ossec/etc/ossec.conf
Info: /Stage[main]/Wazuh::Manager/Concat[manager_ossec.conf]/File[/var/ossec/etc/ossec.conf]: Filebucketed /var/ossec/etc/ossec.conf to puppet with sum 1f8167a0c763fc35819880081eadb609
Notice: /Stage[main]/Wazuh::Manager/Concat[manager_ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}1f8167a0c763fc35819880081eadb609' to '{md5}6215c2f49e5be1280059e351369c64b9'
Notice: /Stage[main]/Wazuh::Manager/Concat[manager_ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
Info: Concat[manager_ossec.conf]: Scheduling refresh of Service[wazuh-manager]
Error: Systemd start for wazuh-manager failed!
journalctl log for wazuh-manager:
-- Logs begin at Wed 2021-09-29 16:11:45 UTC, end at Wed 2021-09-29 17:46:17 UTC. --
Sep 29 17:46:09 agent systemd[1]: Starting Wazuh manager...
Sep 29 17:46:17 agent env[10619]: Configuration not valid: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH/api/configuration/api.yaml): Additional properties are not allowed ('ssl_cipher' was unexpected).
Sep 29 17:46:17 agent env[10619]: wazuh-apid: Configuration error. Exiting
Sep 29 17:46:17 agent systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
Sep 29 17:46:17 agent systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Sep 29 17:46:17 agent systemd[1]: Failed to start Wazuh manager.

Error: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]/ensure: change from 'stopped' to 'running' failed: Systemd start for wazuh-manager failed!
journalctl log for wazuh-manager:
-- Logs begin at Wed 2021-09-29 16:11:45 UTC, end at Wed 2021-09-29 17:46:17 UTC. --
Sep 29 17:46:09 agent systemd[1]: Starting Wazuh manager...
Sep 29 17:46:17 agent env[10619]: Configuration not valid: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH/api/configuration/api.yaml): Additional properties are not allowed ('ssl_cipher' was unexpected).
Sep 29 17:46:17 agent env[10619]: wazuh-apid: Configuration error. Exiting
Sep 29 17:46:17 agent systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
Sep 29 17:46:17 agent systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Sep 29 17:46:17 agent systemd[1]: Failed to start Wazuh manager.

Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 13 events
Info: Class[Wazuh::Manager]: Unscheduling all events on Class[Wazuh::Manager]
Info: Stage[main]: Unscheduling all events on Stage[main]
Notice: Applied catalog in 54.32 seconds
root@agent:~#
```

The modifications of the following PR were made and it was able to deploy without problems.

```
Info: Applying configuration version '1632938806'
Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml]/content:
--- /var/ossec/api/configuration/api.yaml       2021-09-29 18:04:40.783102845 +0000
+++ /tmp/puppet-file20210929-11485-x2cjpq       2021-09-29 18:06:51.670212726 +0000
@@ -11,7 +11,7 @@
   cert: api/configuration/ssl/server.crt
   use_ca: False
   ca: api/configuration/ssl/ca.crt
-  ssl_cipher: ""
+  ssl_ciphers: ""
   ssl_protocol: TLSv1.2
 # Logging configuration
 # Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).

Info: Computing checksum on file /var/ossec/api/configuration/api.yaml
Info: /Stage[main]/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml]: Filebucketed /var/ossec/api/configuration/api.yaml to puppet with sum a57c6f0a8ee8555b1b2f13d251db3fcc
Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml]/content: content changed '{md5}a57c6f0a8ee8555b1b2f13d251db3fcc' to '{md5}350d378b1625838a0449bba3c97fd873'
Info: /Stage[main]/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml]: Scheduling refresh of Service[wazuh-manager]
Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Unscheduling refresh on Service[wazuh-manager]
Notice: Applied catalog in 25.74 seconds
root@agent:~#
```

**Comment by vcerenu** [comment]
The installation was tested on Centos 7 and the same error is generated

```
Oct 01 14:54:53 agent3 systemd [1]: Stopped Wazuh manager.
Oct 01 14:54:53 agent3 systemd [1]: Starting Wazuh manager ...
Oct 01 14:54:57 agent3 env [5898]: Configuration not valid: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH / api / configuration / api.yaml): Additional properties are not allowed ('ssl_cipher' was unexpected).
Oct 01 14:54:57 agent3 env [5898]: wazuh-apid: Configuration error. Exiting
Oct 01 14:54:57 agent3 systemd [1]: wazuh-manager.service: control process exited, code = exited status = 1
Oct 01 14:54:57 agent3 systemd [1]: Failed to start Wazuh manager.
Oct 01 14:54:57 agent3 systemd [1]: Unit wazuh-manager.service entered failed state.
Oct 01 14:54:57 agent3 systemd [1]: wazuh-manager.service failed.
```

Making the proposed change in the PR fixes this error

```
[root @ agent3 ~] # puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Local Retrieving
Info: Loading facts
Info: Caching catalog for agent3
Info: Applying configuration version '1633100220'
Notice: /Stage[main-lex.europa.eu/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml-lex.europa.eu/content:
--- /var/ossec/api/configuration/api.yaml 2021-10-01 14: 54: 50.261778926 +0000
+++ / tmp / puppet-file20211001-5925-z3ychn 2021-10-01 14: 57: 01.509018595 +0000
@@ -11.7 +11.9 @@
   cert: api / configuration / ssl / server.crt
   use_ca: False
   ca: api / configuration / ssl / ca.crt
- ssl_cipher: TLSv1.2
+ ssl_protocol: TLSv1.2
+ ssl_ciphers: ""
+
 # Logging configuration
 # Values ​​for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
 logs:

Info: Computing checksum on file /var/ossec/api/configuration/api.yaml
Info: /Stage[mainiexpress/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml]: Filebucketed /var/ossec/api/configuration/api.yaml to puppet with sum 70be01c50c9aadde5139d112272300d3
Notice: /Stage[main-lex.europa.eu/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml-lex.europa.eu/content: content changed '{md5} 70be01c50c9aadde5139d112272300d3' to '{md5} fc1ae4aa267486
Info: /Stage[main-lex.europa.eu/Wazuh::Manager/File[/var/ossec/api/configuration/api.yaml]: Scheduling refresh of Service [wazuh-manager]
Notice: / Stage [main] / Wazuh :: Manager / Service [wazuh-manager] / ensure: ensure changed 'stopped' to 'running' (corrective)
Info: / Stage [main] / Wazuh :: Manager / Service [wazuh-manager]: Unscheduling refresh on Service [wazuh-manager]
Notice: Applied catalog in 23.70 seconds
```

**Review by vcerenu — APPROVED** [review]
LGTM

**Review by okynos — APPROVED** [review]
LGTM.

**Pull request merged**
