### PR TITLE
Fixes #219: Add sca support for Debian

### LINKED ISSUE #219: No support for Debian sca policies
Unlike **RHEL** there is no separate sca policy support for **Debian**.

There are no sca variables for Debian in agent.pp or params_agent.pp and no section in the corresponding template file.

### PR DESCRIPTION
**Pull request by djmgit**
The PR adds sca support for Debian by introducing the required variables
and changes in the corresponding template.

### CODE REVIEW

**Comment by jm404** [comment]
Hi @djmgit,

We will test it as well as #215 and let you know the results, thanks for contributing!

Best regards,

Jose

**Comment by rshad** [comment]
Hi @djmgit !

Thank you for contributing to Wazuh, we really appreciate our community contributions.

I'm wondering why you decided to add a new dedicated config for `Debian` distribution; As you can see we already have a dedicated config. for all than does not correspond to `CentOS` or `AmazonLinux` OSs.

https://github.com/wazuh/wazuh-puppet/blob/9bb14df62f1485e48d079f263346e522265b9f72/templates/fragments/_sca.erb#L73-L99

I hope you can tell us more about your use case.

Waiting for your reply.

Kr,

Rshad

**Comment by djmgit** [comment]
@rshad Hi, although there is a dedicated config for other non-RHEL type OSs, however what I feel is Debian covers a wide family of OS distributions which is large enough to deserve a separate type of its own, which might help in further customization in future. It might help in providing support for more variety of OSs, for example right now we might not be able to distinguish between Debian and Arch linux or some other flavor of Linux.

However this is my point of view, using ```sca_else``` also makes sense :)

**Comment by rshad** [comment]
Hi @djmgit !

I think this PR is not necessary at this moment. As mentioned, the `else` case covers `Debian` distribution. 

Thank you for contributing.

Kr,

Rshad

**Comment by jm404** [comment]
Hi @djmgit @rshad,

The current SCA configuration block(https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/sca.html#policies) no longer has differences in configuration between OSs so we should use generic configuration settings for this.

Due to the previous, I'm closing this PR, please feel free to open a new one if you have any fixes/improvements to contribute with.

Thanks for your contribution efforts, they're appreciated!

Best regards,

Jose

**Pull request closed without merging**
