### PR TITLE
Update limit parameter

### PR DESCRIPTION
**Pull request by vcerenu**
This PR adds limits parameter into the wazuh-api.yml generator
Issue related https://github.com/wazuh/wazuh-puppet/issues/520

### CODE REVIEW

**Review by okynos — APPROVED** [review]

**Review by davidjiglesias — COMMENTED** [review]
The change is not correct, there are configuration changes including a new parent tag upload_configuration.

**Comment by vcerenu** [comment]
@davidjiglesias I had not seen that difference, I added the upload_configuration tag in the wazuh-api.yml template

**Review by teddytpc1 — APPROVED** [review]
LGTM

**Review by vicferpoy — APPROVED** [review]
LGTM

**Review by okynos — APPROVED** [review]

**Pull request merged**
