### PR TITLE
Authd hostname

### PR DESCRIPTION
**Pull request by tmanninger**
If you run wazuh in the cluster mode, client registration is only accepted on the master node.
Currently, you cannot configure the authd server and the ossec_server_hostname  with different hostnames.

example:
```
    class { 'wazuh::client':
      ossec_server_hostname   => 'master.cluster'
      ossec_authd_hostname    => 'worker.cluster',
    }
```

With this configuration, registration request will be sent to "master.cluster", all logs are sent to "worker.cluster"

### CODE REVIEW

**Comment by tmanninger** [comment]
Where should i add the exampe and the functionality? I cannot find any examples oder functionality description in the README.md

**Comment by manuasir** [comment]
@tmanninger a little example here in the PR description would be alright. 

Thanks

**Comment by tmanninger** [comment]
@manuasir i updated my first post.

**Comment by manuasir** [comment]
@tmanninger ,

It looks good. We will test it and then it will be merged.

Thanks!

**Comment by jm404** [comment]
Hi @tmanninger,

Sorry for the late response. After the Puppet Release 3.9.1_7.1.0, the repository was refactored, making this PR conflict with several parts of our code.

Regarding your PR, let me mention that we recently implemented the ability to register to an IP and report to a different IP for Cluster configurations, you can have a look at it in #136.

Anyway, we are so thankful for community contributions and we appreciate it.

Best regards!

Jose

**Comment by jm404** [comment]
Hi @tmanninger,

I wanted to make some follow-up about this, Did you tried the new configuration parameters?

Best regards

Jose

**Pull request closed without merging**
