### PR TITLE
Add a parameter wazuh_api::manage_nodejs_package

### PR DESCRIPTION
**Pull request by Hexta**
Add a parameter wazuh::wazuh_api::manage_nodejs_package for controlling
nodejs package installation.

if manage_nodejs_package == true (by default) nodejs repo and package
will be installed. Otherwise the repo and the package should be
configured by the user.

### CODE REVIEW

**Comment by Hexta** [comment]
Could anybody please take a look at the PR?

**Comment by manuasir** [comment]
Hello @Hexta. Again, we apologize for the late response. We will take a look and test all your PRs as soon as possible, so please stay tuned here. I'd like to thank you for your contributions, they're very valuable for us and the community.

Regards

**Comment by rshad** [comment]
Hi @Hexta !

Thank you for contributing to Wazuh, this way Wazuh gets improved by the community efforts.

I'll review your changes and I'll be back soon.

KR,

Rshad

**Comment by rshad** [comment]
Hi all!

In this comment, I include the corresponding log when setting `manage_nodejs_package ` to `true` or to `false`.

### `manage_nodejs_package == true`
- **Ubuntu Bionic**
```
       Notice: Compiled catalog for manager_ubuntu_1804 in environment production in 3.29 seconds
       Notice: /Stage[main]/Wazuh::Repo/Package[apt-transport-https]/ensure: created
       Notice: /Stage[main]/Wazuh::Repo/Apt::Key[wazuh]/Package[gnupg]/ensure: created
       Notice: /Stage[main]/Apt/File[sources.list]/mode: mode changed '0644' to '0444'
       Notice: /Stage[main]/Apt/File[sources.list.d]/mode: mode changed '0755' to '0555'
       Notice: /Stage[main]/Apt/File[preferences]/ensure: created
       Notice: /Stage[main]/Apt/File[preferences.d]/mode: mode changed '0755' to '0555'
       Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
       Notice: /Stage[main]/Wazuh::Repo/Apt::Source[wazuh]/Apt::Setting[list-wazuh]/File[/etc/apt/sources.list.d/wazuh.list]/ensure: defined content as '{md5}69093d79d72da7df736f7347ac1cf6ce'
       Notice: /Stage[main]/Wazuh::Repo/Apt::Key[wazuh]/Apt_key[wazuh]/ensure: created
       Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 event
       Notice: /Stage[main]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/content: content changed '{md5}ab73af41699f13fdd81903b5f23d8d00' to '{md5}ae4c1b39ed772935a21b412d730836c1'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/content: content changed '{md5}6663e773bc3ef19ed14853fcaef038cc' to '{md5}efed07c2d4b01112473d8f3c60656499'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/content: content changed '{md5}f83635765eaf65c9204955e11c2eae03' to '{md5}576d3df43e2f4974b43742247d7b9360'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/bin/.process_list]/ensure: defined content as '{md5}4e2ebbeec71161271f2db52cd2c4d864'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}df92424cb18888cc332c1d6dc55dbbc2' to '{md5}d67dece93e3b829aa93aedd0336555d6'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 11 events
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Exec[Updating repositories...]/returns: executed successfully
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Package[nodejs]/ensure: created
       Notice: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: created
       Notice: Applied catalog in 250.17 seconds

```
- **Ubuntu Xenial**
```
       Notice: Compiled catalog for manager_ubuntu_1604 in environment production in 2.95 seconds
       Notice: /Stage[main]/Wazuh::Repo/Package[apt-transport-https]/ensure: created
       Notice: /Stage[main]/Wazuh::Repo/Apt::Key[wazuh]/Apt_key[wazuh]/ensure: created
       Notice: /Stage[main]/Apt/File[sources.list]/mode: mode changed '0644' to '0444'
       Notice: /Stage[main]/Apt/File[sources.list.d]/mode: mode changed '0755' to '0555'
       Notice: /Stage[main]/Apt/File[preferences]/ensure: created
       Notice: /Stage[main]/Apt/File[preferences.d]/mode: mode changed '0755' to '0555'
       Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
       Notice: /Stage[main]/Wazuh::Repo/Apt::Source[wazuh]/Apt::Setting[list-wazuh]/File[/etc/apt/sources.list.d/wazuh.list]/ensure: defined content as '{md5}69093d79d72da7df736f7347ac1cf6ce'
       Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 event
       Notice: /Stage[main]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/content: content changed '{md5}ab73af41699f13fdd81903b5f23d8d00' to '{md5}ae4c1b39ed772935a21b412d730836c1'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/content: content changed '{md5}6663e773bc3ef19ed14853fcaef038cc' to '{md5}efed07c2d4b01112473d8f3c60656499'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/content: content changed '{md5}f83635765eaf65c9204955e11c2eae03' to '{md5}576d3df43e2f4974b43742247d7b9360'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/bin/.process_list]/ensure: defined content as '{md5}4e2ebbeec71161271f2db52cd2c4d864'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}4ce01554349ab8b2708a24574e6a56bd' to '{md5}7090373b421d877da4df5c540850317f'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 11 events
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Exec[Updating repositories...]/returns: executed successfully
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Package[nodejs]/ensure: created
       Notice: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: created

```

- **CentOS 7**
```
       Notice: Compiled catalog for manager_centos_latest in environment production in 4.12 seconds
       Notice: /Stage[main]/Wazuh::Repo/Yumrepo[wazuh]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/content: content changed '{md5}ab73af41699f13fdd81903b5f23d8d00' to '{md5}ae4c1b39ed772935a21b412d730836c1'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/content: content changed '{md5}6663e773bc3ef19ed14853fcaef038cc' to '{md5}efed07c2d4b01112473d8f3c60656499'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/content: content changed '{md5}f83635765eaf65c9204955e11c2eae03' to '{md5}576d3df43e2f4974b43742247d7b9360'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/bin/.process_list]/ensure: defined content as '{md5}4e2ebbeec71161271f2db52cd2c4d864'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}d30e0b40531a96430a67e1d4e85abc11' to '{md5}d44cb3d1e444880733624489f9cbf53c'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 11 events
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Exec[Updating repositories...]/returns: executed successfully
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Package[nodejs]/ensure: created
       Notice: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: created
       Notice: Applied catalog in 176.98 seconds

```
- **AmazonLinux 2**
```
       Notice: Compiled catalog for manager_amazonlinux_latest in environment production in 2.37 seconds
       Notice: /Stage[main]/Wazuh::Repo/Yumrepo[wazuh]/ensure: created


       Notice: /Stage[main]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/content: content changed '{md5}ab73af41699f13fdd81903b5f23d8d00' to '{md5}ae4c1b39ed772935a21b412d730836c1'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/content: content changed '{md5}6663e773bc3ef19ed14853fcaef038cc' to '{md5}efed07c2d4b01112473d8f3c60656499'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/content: content changed '{md5}f83635765eaf65c9204955e11c2eae03' to '{md5}576d3df43e2f4974b43742247d7b9360'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/bin/.process_list]/ensure: defined content as '{md5}4e2ebbeec71161271f2db52cd2c4d864'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}0581c3ef86f5227485875a1541240bd6' to '{md5}719c3b670982b4e1d83b26ef4b8dd077'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 11 events
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Exec[Updating repositories...]/returns: executed successfully
       Notice: /Stage[main]/Wazuh::Wazuh_api::Nodejs/Package[nodejs]/ensure: created
       Notice: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: created
       Notice: Applied catalog in 200.52 seconds

```

### `manage_nodejs_package == false`

- **Ubuntu Bionic: NodeJS already comes installed**
```
       Notice: Compiled catalog for manager_ubuntu_1804 in environment production in 2.64 seconds
       Notice: /Stage[main]/Wazuh::Repo/Package[apt-transport-https]/ensure: created
       Notice: /Stage[main]/Wazuh::Repo/Apt::Key[wazuh]/Package[gnupg]/ensure: created
       Notice: /Stage[main]/Apt/File[sources.list]/mode: mode changed '0644' to '0444'
       Notice: /Stage[main]/Apt/File[sources.list.d]/mode: mode changed '0755' to '0555'
       Notice: /Stage[main]/Apt/File[preferences]/ensure: created
       Notice: /Stage[main]/Apt/File[preferences.d]/mode: mode changed '0755' to '0555'
       Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
       Notice: /Stage[main]/Wazuh::Repo/Apt::Source[wazuh]/Apt::Setting[list-wazuh]/File[/etc/apt/sources.list.d/wazuh.list]/ensure: defined content as '{md5}69093d79d72da7df736f7347ac1cf6ce'
       Notice: /Stage[main]/Wazuh::Repo/Apt::Key[wazuh]/Apt_key[wazuh]/ensure: created
       Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 event
       Notice: /Stage[main]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/content: content changed '{md5}ab73af41699f13fdd81903b5f23d8d00' to '{md5}ae4c1b39ed772935a21b412d730836c1'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/content: content changed '{md5}6663e773bc3ef19ed14853fcaef038cc' to '{md5}efed07c2d4b01112473d8f3c60656499'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/content: content changed '{md5}f83635765eaf65c9204955e11c2eae03' to '{md5}576d3df43e2f4974b43742247d7b9360'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/bin/.process_list]/ensure: defined content as '{md5}4e2ebbeec71161271f2db52cd2c4d864'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}df92424cb18888cc332c1d6dc55dbbc2' to '{md5}d67dece93e3b829aa93aedd0336555d6'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 11 events
       Notice: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: created
       Notice: Applied catalog in 331.24 seconds

```
- **Ubuntu Xenial: No NodeJS is installed**
```
       Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install wazuh-api=3.11.4-1' returned 100: Reading package lists...
       Building dependency tree...
       Reading state information...
       Some packages could not be installed. This may mean that you have
       requested an impossible situation or if you are using the unstable
       distribution that some required packages have not yet been created
       or been moved out of Incoming.
       The following information may help to resolve the situation:

       The following packages have unmet dependencies:
        wazuh-api : Depends: nodejs (>= 4.6.1) but 4.2.6~dfsg-1ubuntu4.2 is to be installed
       E: Unable to correct problems, you have held broken packages.
       Error: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: change from 'purged' to '3.11.4-1' failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install wazuh-api=3.11.4-1' returned 100: Reading package lists...
       Building dependency tree...
       Reading state information...
       Some packages could not be installed. This may mean that you have
       requested an impossible situation or if you are using the unstable
       distribution that some required packages have not yet been created
       or been moved out of Incoming.
       The following information may help to resolve the situation:

       The following packages have unmet dependencies:
        wazuh-api : Depends: nodejs (>= 4.6.1) but 4.2.6~dfsg-1ubuntu4.2 is to be installed
       E: Unable to correct problems, you have held broken packages.
       Notice: /Stage[main]/Wazuh::Wazuh_api/Service[wazuh-api]: Dependency Package[wazuh-api] has failures: true
       Warning: /Stage[main]/Wazuh::Wazuh_api/Service[wazuh-api]: Skipping because of failed dependencies

```

- **CentOS 7: No NodeJS is installed**
```
       Notice: Compiled catalog for manager_centos_latest in environment production in 1.65 seconds
       Notice: /Stage[main]/Wazuh::Repo/Yumrepo[wazuh]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/content: content changed '{md5}ab73af41699f13fdd81903b5f23d8d00' to '{md5}ae4c1b39ed772935a21b412d730836c1'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/shared/default/agent.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/content: content changed '{md5}6663e773bc3ef19ed14853fcaef038cc' to '{md5}efed07c2d4b01112473d8f3c60656499'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/rules/local_rules.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/content: content changed '{md5}f83635765eaf65c9204955e11c2eae03' to '{md5}576d3df43e2f4974b43742247d7b9360'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/owner: owner changed 'ossec' to 'root'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/etc/decoders/local_decoder.xml]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/File[/var/ossec/bin/.process_list]/ensure: defined content as '{md5}4e2ebbeec71161271f2db52cd2c4d864'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}d30e0b40531a96430a67e1d4e85abc11' to '{md5}d44cb3d1e444880733624489f9cbf53c'
       Notice: /Stage[main]/Wazuh::Manager/Concat[ossec.conf]/File[/var/ossec/etc/ossec.conf]/mode: mode changed '0660' to '0640'
       Notice: /Stage[main]/Wazuh::Manager/Service[wazuh-manager]: Triggered 'refresh' from 11 events
       Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install wazuh-api-3.11.4-1' returned 1: Error: Package: wazuh-api-3.11.4-1.x86_64 (wazuh)
           Requires: nodejs >= 4.6
        You could try using --skip-broken to work around the problem
        You could try running: rpm -Va --nofiles --nodigest
       Error: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: change from 'purged' to '3.11.4-1' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install wazuh-api-3.11.4-1' returned 1: Error: Package: wazuh-api-3.11.4-1.x86_64 (wazuh)
           Requires: nodejs >= 4.6
        You could try using --skip-broken to work around the problem
        You could try running: rpm -Va --nofiles --nodigest
       Notice: /Stage[main]/Wazuh::Wazuh_api/Service[wazuh-api]: Dependency Package[wazuh-api] has failures: true
       Warning: /Stage[main]/Wazuh::Wazuh_api/Service[wazuh-api]: Skipping because of failed dependencies

```
- **AmazonLinux 2: No NodeJS is installed**
```
       Error: Could not update: Execution of '/bin/yum -e 0 -y install wazuh-api-3.11.4-1' returned 1: Loaded plugins: ovl, priorities
       Resolving Dependencies
       --> Running transaction check
       ---> Package wazuh-api.x86_64 0:3.11.4-1 will be installed
       --> Processing Dependency: nodejs >= 4.6 for package: wazuh-api-3.11.4-1.x86_64
       --> Finished Dependency Resolution
       Error: Package: wazuh-api-3.11.4-1.x86_64 (wazuh)
           Requires: nodejs >= 4.6
        You could try using --skip-broken to work around the problem
        You could try running: rpm -Va --nofiles --nodigest
       Error: /Stage[main]/Wazuh::Wazuh_api/Package[wazuh-api]/ensure: change from 'purged' to '3.11.4-1' failed: Could not update: Execution of '/bin/yum -e 0 -y install wazuh-api-3.11.4-1' returned 1: Loaded plugins: ovl, priorities

```

Kr,

Rshad

**Pull request merged**
