### PR TITLE
Improve the agent configurability and fix minor issues

### PR DESCRIPTION
**Pull request by JPLachance**
Hello!

I was browsing the Wazuh repository and I figured out that the Wazuh Windows agent configuration generated by Puppet was off compared to https://github.com/wazuh/wazuh/blob/v3.10.2/src/win32/ossec.conf. So here is the fix!

Then I identified some other minor issues and decided to fix them as well. In the end, those are my changes:
* Remove unused parameters in params_agent.pp
* Make the logging log_format configurable
* Remove some duplication between the agent configuration on Linux and Windows
* Improve the Windows agent configuration based on https://github.com/wazuh/wazuh/blob/v3.10.2/src/win32/ossec.conf
* Make the generated ossec.conf file a little bit more readable by fixing ident in fragments
* Remove the duplication in fragments/_sca.erb
* The SCA config now applies for Windows agents too
* Improve the Windows agent syscheck configuration based on https://github.com/wazuh/wazuh/blob/v3.10.2/src/win32/ossec.conf
* Make the cis cat wodle use variable from params_agent.pp
* Make the open-scap wodle use variable from params_agent.pp
* Make the osquery wodle use variable from params_agent.pp
* Make the syscollector wodle use variable from params_agent.pp

Enjoy!

### CODE REVIEW

**Comment by rshad** [comment]
Hi @JPLachance !

Thank you for contributing. Really appreciated.

However after I looked on the changes you made, I found that we already did the majority of them since `wazuh-puppet` ~ 3.11.1_7.5.1. The corresponding PRs are: 
- https://github.com/wazuh/wazuh-puppet/pull/187
- https://github.com/wazuh/wazuh-puppet/pull/190

In this case, the only changes I would pick up from yours, are those which correspond to:
- Parameterized logging template.
- Windows logging format and query event.


- - [`agent.pp`](https://github.com/coveord/wazuh-puppet/blob/3280c77008c06544dbc8703e0c18ef9d5f2ab9a8/manifests/agent.pp#L153)

```ruby
  $logging_log_format                = $wazuh::params_agent::logging_log_format,
```

- - [`wazuh-conf.erb`](https://github.com/coveord/wazuh-puppet/blob/3280c77008c06544dbc8703e0c18ef9d5f2ab9a8/templates/wazuh_agent.conf.erb#L28-L30)
```ruby
  <logging>
    <log_format><%= @logging_log_format %></log_format>
  </logging>
```

- - [`param-agent.pp`](https://github.com/coveord/wazuh-puppet/blob/3280c77008c06544dbc8703e0c18ef9d5f2ab9a8/manifests/params_agent.pp#L386-L405)

```ruby
$logging_log_format = 'plain'
```

```ruby
      $default_local_files = [
        {
          'location'   => 'Application',
          'log_format' => 'eventchannel'
        },
        {
          'location'   => 'Security',
          'log_format' => 'eventchannel',
          'query'      => 'Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and EventID != 5152 and EventID != 5157]'
        },
        {
          'location'   => 'System',
          'log_format' => 'eventchannel'
        },
        {
          'location'   => 'active-response\active-responses.log',
          'log_format' => 'syslog'
        },
      ]
    }
```

I wish you separated the changes in different commits so I could make a `cherry-pick` and let them registered as a contribution of yours.

Let me know if you'll adapt the commit to include these changes only, or if not, I'll adapt it, with no problem.

Kind regards,

Rshad

**Comment by rshad** [comment]
Hi @JPLachance !

As I checked I have no write access to your fork branch, so I created a new branch in the upstream as a copy of yours after applying the merg in local.

To merge this new branch, I created a new PR https://github.com/wazuh/wazuh-puppet/pull/205.

Kr,

Rshad

**Comment by JPLachance** [comment]
Hello @rshad,

I can give you access :) What do you prefer?

This PR is quite old, I see that there are many conflicts now :D

Regards, JP

**Comment by rshad** [comment]
Hi @JPLachance !

No, no need to grant me access to the fork branch.

I already started working in a local branch after making a copy of you commits so they still registered with your account.

check https://github.com/wazuh/wazuh-puppet/pull/205

Kr,

Rshad

**Comment by JPLachance** [comment]
Alright! Thank you :) 

Next time, I'll do multiple commits :D

**Comment by rshad** [comment]
Hi @JPLachance !

Don't worry! :)

Thank you for contributing anyway; that what makes Wazuh get improved.

Kr,

Rshad

**Comment by jm404** [comment]
Done in #189

**Pull request closed without merging**
