### PR TITLE
Use HTTPS for Windows downloads

### PR DESCRIPTION
**Pull request by pheleven**
Changed download location to https.

### CODE REVIEW

**Comment by vcerenu** [comment]
@pheleven Can you create this PR on the 4.3 branch? within the master branch we have the development of the next release

**Comment by pheleven** [comment]
> @pheleven Can you create this PR on the 4.3 branch? within the master branch we have the development of the next release

I moved it, let me know if you need a new PR instead.

**Comment by vcerenu** [comment]
> > @pheleven Can you create this PR on the 4.3 branch? within the master branch we have the development of the next release
> 
> I moved it, let me know if you need a new PR instead.

The master base that you are using has several changes on the 4.3 branch, if you check the files you see that there are many changes that are being impacted, if possible, create a new PR starting from the 4.3 branch so that only the change is applied in the settings you mentioned.
I could do it in a separate PR but I didn't want to step on your commit

**Comment by pheleven** [comment]
Sorry about that - https://github.com/wazuh/wazuh-puppet/pull/498

**Pull request closed without merging**
