### PR TITLE
add OracleLinux to manager and agent

### PR DESCRIPTION
**Pull request by rwaffen**

### CODE REVIEW

**Comment by jm404** [comment]
Hi @rwaffen,

As Oracle Linux is based on RedHat, the same configurations should apply to it. 

We will run some tests on this to verify everything works fine and update as soon as we have conclusions about it. 

Best regards

Jose

**Comment by rwaffen** [comment]
I see there are some failed checks, but cannot see the results. :-/

**Comment by jm404** [comment]
Hi @rwaffen, don't worry about it, we are implementing automated tests for public PR's that require some configuration and setup yet. 

Best regards

Jose

**Comment by rwaffen** [comment]
Hi... how far are you  with the tests? Can we expect some results soon? 😃

**Comment by jm404** [comment]
Hi @rwaffen,

I updated your PR to `devel` branch instead of master and resolved conflicts. We are testing it and will update you with the results as soon as possible.

Thanks again for contributing and for your patience!

Best regards,

Jose

**Comment by jm404** [comment]
Hi @rwaffen,

By your leave, I added the changes to the `agent.pp` manifest also.

I successfully installed the Wazuh Manager and Agent on Oracle Linux 7. No errors appeared on logs and alerts were properly generated and indexed.

Also, the changes passed the tests so I'm merging this.

Thanks for your contribution, it's really appreciated!

Best regards,

Jose

**Comment by rwaffen** [comment]
many thanks! 😄

**Pull request merged**
