### PR TITLE
wodle ciscat support

### PR DESCRIPTION
**Pull request by tmanninger**
Currently there is no support for the wodle module "ciscat"

This pull request adds support for ciscat

### CODE REVIEW

**Comment by manuasir** [comment]
Hi @tmanninger ,

Thank you for this collaboration, we will review and merge it ASAP.

Cheers

**Comment by tmanninger** [comment]
Hi @LuisGi93 

but java is needed by cis cat and not by wazuh.
I also created a cis cat puppet modul on local repository, which installs the ciscat (and java package) .

So i think, java should be installed by the ciscat installer and not by wazuh.

**Comment by tmanninger** [comment]
Any news?

**Comment by jm404** [comment]
Hi @tmanninger,

We did a little refactor in Puppet Release 3.9.1_7.1.0. One of those changes were adding compatibility with wodles.

Said changes have been currently merged on master so your PR has conflicts with it.

Please have a look at the new repository and the wodles implemented and feel free to edit your PR or open a new one or a new issue.

Best regards,

Jose

**Comment by jm404** [comment]
Hi @tmanninger ,

Did you try the new parameters? 

Community feedback is always appreciated!

Best regards,

Jose

**Comment by rshad** [comment]
Hi all,

The changes @jm404 mentioned, were added in https://github.com/wazuh/wazuh-puppet/commit/5cab4bfb688a946ec224f30c6bfd72efab737413.

Kr,

Rshad

**Pull request closed without merging**
